name: Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install
      - name: Test
        run: yarn test:coverage
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: sukhiboi-build
          path: dist
          retention-days: 1

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v2
      - uses: actions/download-artifact@v3
        with:
          name: sukhiboi-build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "."
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
